export const basePath = "/";
export const mainPath = "/main";
export const genres = "/genre";
export const overviewPath = mainPath + "/overview";
export const hiphopPath = genres + "/hiphop";
export const heelsPath = genres + "/heels";
export const streetjazzPath = genres + "/streetjazz";
export const polePath = genres + "/pole";
export const openPath = genres + "/open";
